// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbsolutePath(arg1) {
  return window['go']['main']['App']['AbsolutePath'](arg1);
}

export function CacheFileExists(arg1, arg2) {
  return window['go']['main']['App']['CacheFileExists'](arg1, arg2);
}

export function CopyFileToCache(arg1, arg2) {
  return window['go']['main']['App']['CopyFileToCache'](arg1, arg2);
}

export function Copyfile(arg1, arg2) {
  return window['go']['main']['App']['Copyfile'](arg1, arg2);
}

export function DownloadValidateReport() {
  return window['go']['main']['App']['DownloadValidateReport']();
}

export function ExitApp() {
  return window['go']['main']['App']['ExitApp']();
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function GetCachePath(arg1) {
  return window['go']['main']['App']['GetCachePath'](arg1);
}

export function GetChinaAreaMap() {
  return window['go']['main']['App']['GetChinaAreaMap']();
}

export function GetChinaAreaStr() {
  return window['go']['main']['App']['GetChinaAreaStr']();
}

export function GetCurrentOSUser() {
  return window['go']['main']['App']['GetCurrentOSUser']();
}

export function GetEnv() {
  return window['go']['main']['App']['GetEnv']();
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function Makedir(arg1) {
  return window['go']['main']['App']['Makedir'](arg1);
}

export function Movefile(arg1, arg2) {
  return window['go']['main']['App']['Movefile'](arg1, arg2);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function OpenFileInExplorer(arg1) {
  return window['go']['main']['App']['OpenFileInExplorer'](arg1);
}

export function OpenSaveDialog(arg1) {
  return window['go']['main']['App']['OpenSaveDialog'](arg1);
}

export function ReadFile(arg1, arg2) {
  return window['go']['main']['App']['ReadFile'](arg1, arg2);
}

export function Readdir(arg1) {
  return window['go']['main']['App']['Readdir'](arg1);
}

export function Removefile(arg1) {
  return window['go']['main']['App']['Removefile'](arg1);
}

export function ShowMessageBox(arg1) {
  return window['go']['main']['App']['ShowMessageBox'](arg1);
}

export function ValidateData(arg1) {
  return window['go']['main']['App']['ValidateData'](arg1);
}
