// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {db} from '../models';

export function AbsolutePath(arg1:string):Promise<main.FlagResult>;

export function BackupDatabase():Promise<any>;

export function CancelImport(arg1:string):Promise<any>;

export function CheckAndExportToExcel(arg1:string):Promise<boolean>;

export function CheckDuplicateRecords(arg1:string):Promise<boolean>;

export function ClearTableData(arg1:string):Promise<void>;

export function Copyfile(arg1:string,arg2:string):Promise<main.FlagResult>;

export function ExitApp():Promise<void>;

export function ExportAllData(arg1:string):Promise<main.ExportResult>;

export function ExportCheckResultsToExcel(arg1:string):Promise<string>;

export function ExportData(arg1:string,arg2:string,arg3:Record<string, any>):Promise<main.ExportResult>;

export function FileExists(arg1:string):Promise<main.FlagResult>;

export function GetAreaConfig():Promise<db.QueryResult>;

export function GetCurrentOSUser():Promise<string>;

export function GetDataCheckDetail(arg1:string,arg2:string):Promise<any>;

export function GetDataCheckList(arg1:string,arg2:number,arg3:number):Promise<any>;

export function GetDataCheckListAttachment2(arg1:number,arg2:number):Promise<any>;

export function GetDataCheckListTable1(arg1:number,arg2:number):Promise<any>;

export function GetDataCheckListTable2(arg1:number,arg2:number):Promise<any>;

export function GetDataCheckListTable3(arg1:number,arg2:number):Promise<any>;

export function GetEnv():Promise<main.EnvResult>;

export function GetExportHistory(arg1:number,arg2:number):Promise<any>;

export function GetFileInfo(arg1:string):Promise<main.FileInfo>;

export function GetImportHistory(arg1:number,arg2:number):Promise<any>;

export function GetImportProcess(arg1:string):Promise<main.ImportProcess>;

export function GetMergeHistory(arg1:number,arg2:number):Promise<any>;

export function GetPasswordInfo():Promise<db.QueryResult>;

export function GetSystemInfo():Promise<any>;

export function GetSystemSettings():Promise<Array<main.SystemSetting>>;

export function ImportAttachment2(arg1:string,arg2:string):Promise<main.DataImportResult>;

export function ImportEnterpriseList(arg1:string):Promise<main.QueryResult>;

export function ImportKeyEquipmentList(arg1:string):Promise<main.QueryResult>;

export function ImportTable1(arg1:string,arg2:string):Promise<main.DataImportResult>;

export function ImportTable2(arg1:string,arg2:string):Promise<main.DataImportResult>;

export function ImportTable3(arg1:string,arg2:string):Promise<main.DataImportResult>;

export function Login(arg1:string):Promise<db.QueryResult>;

export function Makedir(arg1:string):Promise<main.FlagResult>;

export function ManualDataCheck(arg1:main.ManualCheckResult):Promise<main.DataCheckResult>;

export function ManualDataCheckAttachment2(arg1:main.ManualCheckResult):Promise<main.DataCheckResult>;

export function ManualDataCheckTable1(arg1:main.ManualCheckResult):Promise<main.DataCheckResult>;

export function ManualDataCheckTable2(arg1:main.ManualCheckResult):Promise<main.DataCheckResult>;

export function ManualDataCheckTable3(arg1:main.ManualCheckResult):Promise<main.DataCheckResult>;

export function MergeDatabase(arg1:string,arg2:string):Promise<main.MergeResult>;

export function ModelDataCheck():Promise<main.DataCheckResult>;

export function ModelDataCheckAttachment2():Promise<main.DataCheckResult>;

export function ModelDataCheckTable1():Promise<main.DataCheckResult>;

export function ModelDataCheckTable2():Promise<main.DataCheckResult>;

export function ModelDataCheckTable3():Promise<main.DataCheckResult>;

export function Movefile(arg1:string,arg2:string):Promise<main.FlagResult>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenFileDialog(arg1:main.FileDialogOptions):Promise<main.FileDialogResult>;

export function OpenSaveDialog(arg1:main.FileDialogOptions):Promise<main.FileDialogResult>;

export function ReadFile(arg1:string,arg2:boolean):Promise<Array<number>>;

export function Readdir(arg1:string):Promise<main.FlagResult>;

export function Removefile(arg1:string):Promise<main.FlagResult>;

export function RestoreDatabase(arg1:string):Promise<any>;

export function SaveAreaConfig(arg1:main.AreaConfig):Promise<db.QueryResult>;

export function SetUserPassword(arg1:string):Promise<db.QueryResult>;

export function ShowMessageBox(arg1:main.MessageBoxOptions):Promise<main.MessageBoxResult>;

export function UpdateSystemSetting(arg1:string,arg2:string):Promise<any>;

export function ValidateEnterpriseListFile(arg1:string):Promise<main.QueryResult>;

export function ValidateKeyEquipmentListFile(arg1:string):Promise<main.QueryResult>;

export function ValidateMergeSource(arg1:string):Promise<any>;
