// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {db} from '../models';
import {context} from '../models';

export function AbsolutePath(arg1:string):Promise<main.FlagResult>;

export function CacheFileExists(arg1:string,arg2:string):Promise<db.QueryResult>;

export function CancelImport(arg1:string):Promise<any>;

export function CopyFileToCache(arg1:string,arg2:string):Promise<db.QueryResult>;

export function Copyfile(arg1:string,arg2:string):Promise<main.FlagResult>;

export function ExitApp():Promise<void>;

export function ExportAllData(arg1:string):Promise<main.ExportResult>;

export function ExportData(arg1:string,arg2:string,arg3:Record<string, any>):Promise<main.ExportResult>;

export function FileExists(arg1:string):Promise<main.FlagResult>;

export function GetAreaConfig():Promise<db.QueryResult>;

export function GetCachePath(arg1:string):Promise<string>;

export function GetCtx():Promise<context.Context>;

export function GetCurrentOSUser():Promise<string>;

export function GetDB():Promise<db.Database>;

export function GetEnterpriseNameByCreditCode(arg1:string):Promise<string>;

export function GetEnv():Promise<main.EnvResult>;

export function GetEquipmentByCreditCode(arg1:string):Promise<db.QueryResult>;

export function GetExportHistory(arg1:number,arg2:number):Promise<any>;

export function GetFileInfo(arg1:string):Promise<main.FileInfo>;

export function GetImportHistory(arg1:number,arg2:number):Promise<any>;

export function GetImportProcess(arg1:string):Promise<main.ImportProcess>;

export function GetImportRecordsByFileType(arg1:string):Promise<db.QueryResult>;

export function GetMergeHistory(arg1:number,arg2:number):Promise<any>;

export function GetPasswordInfo():Promise<db.QueryResult>;

export function ImportEnterpriseList(arg1:string):Promise<db.QueryResult>;

export function ImportKeyEquipmentList(arg1:string):Promise<db.QueryResult>;

export function InsertImportRecord(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function IsEnterpriseListExist():Promise<boolean>;

export function IsEquipmentListExist():Promise<boolean>;

export function Login(arg1:string):Promise<db.QueryResult>;

export function Makedir(arg1:string):Promise<main.FlagResult>;

export function MergeDatabase(arg1:string,arg2:string):Promise<main.MergeResult>;

export function ModelDataCheckAttachment2():Promise<db.QueryResult>;

export function ModelDataCheckReportDownload(arg1:string):Promise<db.QueryResult>;

export function ModelDataCheckTable1():Promise<db.QueryResult>;

export function ModelDataCheckTable2():Promise<db.QueryResult>;

export function ModelDataCheckTable3():Promise<db.QueryResult>;

export function ModelDataCoverAttachment2(arg1:Array<string>):Promise<db.QueryResult>;

export function ModelDataCoverTable1(arg1:Array<string>):Promise<db.QueryResult>;

export function ModelDataCoverTable2(arg1:Array<string>):Promise<db.QueryResult>;

export function ModelDataCoverTable3(arg1:Array<string>):Promise<db.QueryResult>;

export function Movefile(arg1:string,arg2:string):Promise<main.FlagResult>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenFileDialog(arg1:main.FileDialogOptions):Promise<main.FileDialogResult>;

export function OpenSaveDialog(arg1:main.FileDialogOptions):Promise<main.FileDialogResult>;

export function ReadFile(arg1:string,arg2:boolean):Promise<Array<number>>;

export function Readdir(arg1:string):Promise<main.FlagResult>;

export function Removefile(arg1:string):Promise<main.FlagResult>;

export function SM4Decrypt(arg1:string):Promise<string>;

export function SM4Encrypt(arg1:string):Promise<string>;

export function SaveAreaConfig(arg1:main.AreaConfig):Promise<db.QueryResult>;

export function SetUserPassword(arg1:string):Promise<db.QueryResult>;

export function ShowMessageBox(arg1:main.MessageBoxOptions):Promise<main.MessageBoxResult>;

export function ValidateAttachment2File(arg1:string,arg2:boolean):Promise<db.QueryResult>;

export function ValidateEnterpriseListFile(arg1:string):Promise<db.QueryResult>;

export function ValidateKeyEquipmentListFile(arg1:string):Promise<db.QueryResult>;

export function ValidateMergeSource(arg1:string):Promise<any>;

export function ValidateTable1File(arg1:string,arg2:boolean):Promise<db.QueryResult>;

export function ValidateTable2File(arg1:string,arg2:boolean):Promise<db.QueryResult>;

export function ValidateTable3File(arg1:string,arg2:boolean):Promise<db.QueryResult>;
