// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbsolutePath(arg1) {
  return window['go']['main']['App']['AbsolutePath'](arg1);
}

export function CacheFileExists(arg1, arg2) {
  return window['go']['main']['App']['CacheFileExists'](arg1, arg2);
}

export function CancelImport(arg1) {
  return window['go']['main']['App']['CancelImport'](arg1);
}

export function ConfirmDataAttachment2(arg1) {
  return window['go']['main']['App']['ConfirmDataAttachment2'](arg1);
}

export function ConfirmDataTable1(arg1) {
  return window['go']['main']['App']['ConfirmDataTable1'](arg1);
}

export function ConfirmDataTable2(arg1) {
  return window['go']['main']['App']['ConfirmDataTable2'](arg1);
}

export function ConfirmDataTable3(arg1) {
  return window['go']['main']['App']['ConfirmDataTable3'](arg1);
}

export function CopyFileToCache(arg1, arg2) {
  return window['go']['main']['App']['CopyFileToCache'](arg1, arg2);
}

export function Copyfile(arg1, arg2) {
  return window['go']['main']['App']['Copyfile'](arg1, arg2);
}

export function ExitApp() {
  return window['go']['main']['App']['ExitApp']();
}

export function ExportDBData(arg1) {
  return window['go']['main']['App']['ExportDBData'](arg1);
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function GetAreaConfig() {
  return window['go']['main']['App']['GetAreaConfig']();
}

export function GetCachePath(arg1) {
  return window['go']['main']['App']['GetCachePath'](arg1);
}

export function GetCtx() {
  return window['go']['main']['App']['GetCtx']();
}

export function GetCurrentOSUser() {
  return window['go']['main']['App']['GetCurrentOSUser']();
}

export function GetDB() {
  return window['go']['main']['App']['GetDB']();
}

export function GetEnterpriseInfoByCreditCode(arg1) {
  return window['go']['main']['App']['GetEnterpriseInfoByCreditCode'](arg1);
}

export function GetEnv() {
  return window['go']['main']['App']['GetEnv']();
}

export function GetEquipmentByCreditCode(arg1) {
  return window['go']['main']['App']['GetEquipmentByCreditCode'](arg1);
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetImportHistory(arg1, arg2) {
  return window['go']['main']['App']['GetImportHistory'](arg1, arg2);
}

export function GetImportProcess(arg1) {
  return window['go']['main']['App']['GetImportProcess'](arg1);
}

export function GetImportRecordsByFileType(arg1) {
  return window['go']['main']['App']['GetImportRecordsByFileType'](arg1);
}

export function GetMergeHistory(arg1, arg2) {
  return window['go']['main']['App']['GetMergeHistory'](arg1, arg2);
}

export function GetPasswordInfo() {
  return window['go']['main']['App']['GetPasswordInfo']();
}

export function ImportEnterpriseList(arg1) {
  return window['go']['main']['App']['ImportEnterpriseList'](arg1);
}

export function ImportKeyEquipmentList(arg1) {
  return window['go']['main']['App']['ImportKeyEquipmentList'](arg1);
}

export function InsertImportRecord(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InsertImportRecord'](arg1, arg2, arg3, arg4);
}

export function IsEnterpriseListExist() {
  return window['go']['main']['App']['IsEnterpriseListExist']();
}

export function IsEquipmentListExist() {
  return window['go']['main']['App']['IsEquipmentListExist']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Makedir(arg1) {
  return window['go']['main']['App']['Makedir'](arg1);
}

export function MergeDatabase(arg1, arg2) {
  return window['go']['main']['App']['MergeDatabase'](arg1, arg2);
}

export function ModelDataCheckAttachment2() {
  return window['go']['main']['App']['ModelDataCheckAttachment2']();
}

export function ModelDataCheckReportDownload(arg1) {
  return window['go']['main']['App']['ModelDataCheckReportDownload'](arg1);
}

export function ModelDataCheckTable1() {
  return window['go']['main']['App']['ModelDataCheckTable1']();
}

export function ModelDataCheckTable2() {
  return window['go']['main']['App']['ModelDataCheckTable2']();
}

export function ModelDataCheckTable3() {
  return window['go']['main']['App']['ModelDataCheckTable3']();
}

export function ModelDataCoverAttachment2(arg1) {
  return window['go']['main']['App']['ModelDataCoverAttachment2'](arg1);
}

export function ModelDataCoverTable1(arg1) {
  return window['go']['main']['App']['ModelDataCoverTable1'](arg1);
}

export function ModelDataCoverTable2(arg1) {
  return window['go']['main']['App']['ModelDataCoverTable2'](arg1);
}

export function ModelDataCoverTable3(arg1) {
  return window['go']['main']['App']['ModelDataCoverTable3'](arg1);
}

export function Movefile(arg1, arg2) {
  return window['go']['main']['App']['Movefile'](arg1, arg2);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function OpenSaveDialog(arg1) {
  return window['go']['main']['App']['OpenSaveDialog'](arg1);
}

export function QueryDataAttachment2() {
  return window['go']['main']['App']['QueryDataAttachment2']();
}

export function QueryDataDetailTable1(arg1) {
  return window['go']['main']['App']['QueryDataDetailTable1'](arg1);
}

export function QueryDataTable1() {
  return window['go']['main']['App']['QueryDataTable1']();
}

export function QueryDataTable2() {
  return window['go']['main']['App']['QueryDataTable2']();
}

export function QueryDataTable3() {
  return window['go']['main']['App']['QueryDataTable3']();
}

export function QueryExportData() {
  return window['go']['main']['App']['QueryExportData']();
}

export function ReadFile(arg1, arg2) {
  return window['go']['main']['App']['ReadFile'](arg1, arg2);
}

export function Readdir(arg1) {
  return window['go']['main']['App']['Readdir'](arg1);
}

export function Removefile(arg1) {
  return window['go']['main']['App']['Removefile'](arg1);
}

export function SM4Decrypt(arg1) {
  return window['go']['main']['App']['SM4Decrypt'](arg1);
}

export function SM4Encrypt(arg1) {
  return window['go']['main']['App']['SM4Encrypt'](arg1);
}

export function SaveAreaConfig(arg1) {
  return window['go']['main']['App']['SaveAreaConfig'](arg1);
}

export function SetUserPassword(arg1) {
  return window['go']['main']['App']['SetUserPassword'](arg1);
}

export function ShowMessageBox(arg1) {
  return window['go']['main']['App']['ShowMessageBox'](arg1);
}

export function ValidateAttachment2File(arg1, arg2) {
  return window['go']['main']['App']['ValidateAttachment2File'](arg1, arg2);
}

export function ValidateEnterpriseListFile(arg1) {
  return window['go']['main']['App']['ValidateEnterpriseListFile'](arg1);
}

export function ValidateKeyEquipmentListFile(arg1) {
  return window['go']['main']['App']['ValidateKeyEquipmentListFile'](arg1);
}

export function ValidateMergeSource(arg1) {
  return window['go']['main']['App']['ValidateMergeSource'](arg1);
}

export function ValidateTable1File(arg1, arg2) {
  return window['go']['main']['App']['ValidateTable1File'](arg1, arg2);
}

export function ValidateTable2File(arg1, arg2) {
  return window['go']['main']['App']['ValidateTable2File'](arg1, arg2);
}

export function ValidateTable3File(arg1, arg2) {
  return window['go']['main']['App']['ValidateTable3File'](arg1, arg2);
}
