// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbsolutePath(arg1) {
  return window['go']['main']['App']['AbsolutePath'](arg1);
}

export function CacheFileExists(arg1) {
  return window['go']['main']['App']['CacheFileExists'](arg1);
}

export function CancelImport(arg1) {
  return window['go']['main']['App']['CancelImport'](arg1);
}

export function CheckAndExportToExcel(arg1) {
  return window['go']['main']['App']['CheckAndExportToExcel'](arg1);
}

export function CopyFileToCache(arg1) {
  return window['go']['main']['App']['CopyFileToCache'](arg1);
}

export function Copyfile(arg1, arg2) {
  return window['go']['main']['App']['Copyfile'](arg1, arg2);
}

export function ExitApp() {
  return window['go']['main']['App']['ExitApp']();
}

export function ExportAllData(arg1) {
  return window['go']['main']['App']['ExportAllData'](arg1);
}

export function ExportCheckResultsToExcel(arg1) {
  return window['go']['main']['App']['ExportCheckResultsToExcel'](arg1);
}

export function ExportData(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportData'](arg1, arg2, arg3);
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function GetAreaConfig() {
  return window['go']['main']['App']['GetAreaConfig']();
}

export function GetCurrentOSUser() {
  return window['go']['main']['App']['GetCurrentOSUser']();
}

export function GetDB() {
  return window['go']['main']['App']['GetDB']();
}

export function GetDataCheckDetail(arg1, arg2) {
  return window['go']['main']['App']['GetDataCheckDetail'](arg1, arg2);
}

export function GetDataCheckList(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDataCheckList'](arg1, arg2, arg3);
}

export function GetDataCheckListAttachment2(arg1, arg2) {
  return window['go']['main']['App']['GetDataCheckListAttachment2'](arg1, arg2);
}

export function GetDataCheckListTable1(arg1, arg2) {
  return window['go']['main']['App']['GetDataCheckListTable1'](arg1, arg2);
}

export function GetDataCheckListTable2(arg1, arg2) {
  return window['go']['main']['App']['GetDataCheckListTable2'](arg1, arg2);
}

export function GetDataCheckListTable3(arg1, arg2) {
  return window['go']['main']['App']['GetDataCheckListTable3'](arg1, arg2);
}

export function GetEnv() {
  return window['go']['main']['App']['GetEnv']();
}

export function GetExportHistory(arg1, arg2) {
  return window['go']['main']['App']['GetExportHistory'](arg1, arg2);
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetImportHistory(arg1, arg2) {
  return window['go']['main']['App']['GetImportHistory'](arg1, arg2);
}

export function GetImportProcess(arg1) {
  return window['go']['main']['App']['GetImportProcess'](arg1);
}

export function GetImportRecordsByFileType(arg1) {
  return window['go']['main']['App']['GetImportRecordsByFileType'](arg1);
}

export function GetMergeHistory(arg1, arg2) {
  return window['go']['main']['App']['GetMergeHistory'](arg1, arg2);
}

export function GetPasswordInfo() {
  return window['go']['main']['App']['GetPasswordInfo']();
}

export function ImportEnterpriseList(arg1) {
  return window['go']['main']['App']['ImportEnterpriseList'](arg1);
}

export function ImportKeyEquipmentList(arg1) {
  return window['go']['main']['App']['ImportKeyEquipmentList'](arg1);
}

export function InsertImportRecord(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InsertImportRecord'](arg1, arg2, arg3, arg4);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Makedir(arg1) {
  return window['go']['main']['App']['Makedir'](arg1);
}

export function ManualDataCheck(arg1) {
  return window['go']['main']['App']['ManualDataCheck'](arg1);
}

export function ManualDataCheckAttachment2(arg1) {
  return window['go']['main']['App']['ManualDataCheckAttachment2'](arg1);
}

export function ManualDataCheckTable1(arg1) {
  return window['go']['main']['App']['ManualDataCheckTable1'](arg1);
}

export function ManualDataCheckTable2(arg1) {
  return window['go']['main']['App']['ManualDataCheckTable2'](arg1);
}

export function ManualDataCheckTable3(arg1) {
  return window['go']['main']['App']['ManualDataCheckTable3'](arg1);
}

export function MergeDatabase(arg1, arg2) {
  return window['go']['main']['App']['MergeDatabase'](arg1, arg2);
}

export function ModelDataCheck() {
  return window['go']['main']['App']['ModelDataCheck']();
}

export function ModelDataCheckAttachment2() {
  return window['go']['main']['App']['ModelDataCheckAttachment2']();
}

export function ModelDataCheckTable1() {
  return window['go']['main']['App']['ModelDataCheckTable1']();
}

export function ModelDataCheckTable2() {
  return window['go']['main']['App']['ModelDataCheckTable2']();
}

export function ModelDataCheckTable3() {
  return window['go']['main']['App']['ModelDataCheckTable3']();
}

export function Movefile(arg1, arg2) {
  return window['go']['main']['App']['Movefile'](arg1, arg2);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function OpenSaveDialog(arg1) {
  return window['go']['main']['App']['OpenSaveDialog'](arg1);
}

export function ReadFile(arg1, arg2) {
  return window['go']['main']['App']['ReadFile'](arg1, arg2);
}

export function Readdir(arg1) {
  return window['go']['main']['App']['Readdir'](arg1);
}

export function Removefile(arg1) {
  return window['go']['main']['App']['Removefile'](arg1);
}

export function SaveAreaConfig(arg1) {
  return window['go']['main']['App']['SaveAreaConfig'](arg1);
}

export function SetUserPassword(arg1) {
  return window['go']['main']['App']['SetUserPassword'](arg1);
}

export function ShowMessageBox(arg1) {
  return window['go']['main']['App']['ShowMessageBox'](arg1);
}

export function ValidateAttachment2File(arg1) {
  return window['go']['main']['App']['ValidateAttachment2File'](arg1);
}

export function ValidateEnterpriseListFile(arg1) {
  return window['go']['main']['App']['ValidateEnterpriseListFile'](arg1);
}

export function ValidateKeyEquipmentListFile(arg1) {
  return window['go']['main']['App']['ValidateKeyEquipmentListFile'](arg1);
}

export function ValidateMergeSource(arg1) {
  return window['go']['main']['App']['ValidateMergeSource'](arg1);
}

export function ValidateTable1File(arg1) {
  return window['go']['main']['App']['ValidateTable1File'](arg1);
}

export function ValidateTable2File(arg1) {
  return window['go']['main']['App']['ValidateTable2File'](arg1);
}

export function ValidateTable3File(arg1) {
  return window['go']['main']['App']['ValidateTable3File'](arg1);
}
